const path = require('path');

module.exports = {
    GQL_HOSTNAME: process.env['METRIFFIC_GQL_HOSTNAME'],
    GQL_PORT: 4000,
    GQL_ENDPOINT: 'workspace_manager',

    USERSPACE_ROOT: process.env['METRIFFIC_USERSPACE_ROOT'],

    WORKSPACE_MANAGER_PRIVATE_KEY_FILE: process.env['METRIFFIC_WORKSPACE_MANAGER_PRIVATE_KEY_FILE'],

    RSYNC_SERVER_HOST_KEY_FILE: process.env['METRIFFIC_RSYNC_SERVER_HOST_KEY_FILE'],
    RSYNC_SERVER_PORT : 7000
}
  
